### ISSUE TITLE
Request Timed Out?

### ISSUE THREAD

**Issue by darbyjack** [surgeplay/Visage#26]
Sorry if this is easy to fix or it's a little stupid mistake but I'm getting 
`com.surgeplay.visage.distributor.exception.RenderFailedException: Request timed out
	at com.surgeplay.visage.distributor.VisageDistributor.renderRpc(VisageDistributor.java:290)
	at com.surgeplay.visage.distributor.VisageHandler.handle(VisageHandler.java:368)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ResourceHandler.handle(ResourceHandler.java:287)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at com.surgeplay.visage.distributor.glue.HeaderHandler.handle(HeaderHandler.java:50)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:521)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
	at java.lang.Thread.run(Thread.java:748)`
When I try to render a head or anything for that matter under Distributor?

Hope you can help,
Thanks.

**Comment by exaskye** [comment]
You need at least one renderer connected.

**Comment by darbyjack** [comment]
Sorry, 
can you explain a little bit?

I setup a RabbitMQ server and it says Connected at IP.

**Comment by exaskye** [comment]
You need to run *two* copies of Visage, one in Distributor mode and one in Renderer mode. The Distributor just handles distributing jobs and running the web server; the Renderer does the actual avatar renders.

Your request is timing out because there's nobody to respond to it.

**Comment by darbyjack** [comment]
Awesome, okay.

I tried to run a 2nd copy (the Rendered) and I get this now?
`@02:00:55.399           Main thread  INFO: Starting Visage v2.0.115 as a renderer
@02:00:55.540           Main thread  INFO: Renderer name is 'jake'
@02:00:55.541           Main thread  INFO: Reading configuration from conf/renderer.conf
@02:00:55.541           Main thread  INFO: Press Ctrl+C to shutdown Visage.
@02:00:55.543       Renderer thread  INFO: Setting up LWJGL
java.lang.RuntimeException: Failed to initialize GLFW
        at com.surgeplay.visage.renderer.VisageRenderer.run(VisageRenderer.java:93)
@02:00:55.647       Renderer thread ERROR: A fatal error has occurred while setting up the renderer.`
Thanks again!

**Comment by exaskye** [comment]
The renderer only works on computers with a GPU and OpenGL3.1 or higher support.

**Comment by darbyjack** [comment]
So using a Ubuntu 16.04 VM will not work?

**Comment by exaskye** [comment]
No.

**Comment by darbyjack** [comment]
Ah, okay, thanks for your time. I guess I won't be able to use it. Looks cool though!

**Comment by exaskye** [comment]
Well, you can always use the [official hosted service](https://visage.surgeplay.com).

**Comment by darbyjack** [comment]
Ya, I guess I will. Thanks. Was just seeing what all I could do!
