### ISSUE TITLE
RenderFailedException

### ISSUE THREAD

**Issue by niklaswa** [surgeplay/Visage#5]
I've a visage server placed behind a nginx proxy and when i request the front page, it says "It works". When i request `/bust/Niklas` i'm getting redirected to `/full/256/e0276ad91cd64c8db8f7ff97e75c5982`, but then it says:

> com.surgeplay.visage.master.exception.RenderFailedException: Request timed out
>   at com.surgeplay.visage.master.VisageMaster.renderRpc(VisageMaster.java:293)
>   at com.surgeplay.visage.master.VisageHandler.handle(VisageHandler.java:445)
>   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:118)
>   at org.eclipse.jetty.server.handler.ResourceHandler.handle(ResourceHandler.java:438)
>   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:118)
>   at com.surgeplay.visage.master.glue.HeaderHandler.handle(HeaderHandler.java:50)
>   at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:383)
>   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:118)
>   at org.eclipse.jetty.server.Server.handle(Server.java:512)
>   at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:291)
>   at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
>   at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:238)
>   at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
>   at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:53)
>   at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:191)
>   at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:126)
>   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
>   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
>   at java.lang.Thread.run(Thread.java:745)

I hope you can help me with my problem.

**Comment by niklaswa** [comment]
Hoops, nevermind.
Maybe you need to mention, that you need atleast one slave :smile:
